-- Provider-neutral embedding generations.
--
-- The original schema was sufficient for the deterministic 64-dimensional
-- fixture, but a fixed vector typmod makes it impossible to keep that fixture
-- beside a real 384-dimensional provider.  This migration preserves the
-- existing rows while making the generation descriptor and lifecycle
-- explicit.  Vector indexes remain dimension-specific expression indexes;
-- an unbounded vector column is never indexed without a fixed cast.

alter table embedding_generations
  add column if not exists input_strategy text,
  add column if not exists configuration_hash text,
  add column if not exists runtime text,
  add column if not exists retired_at timestamptz,
  add column if not exists failure_reason text,
  add column if not exists updated_at timestamptz not null default now();

-- Existing generations predate the complete descriptor.  The fallback values
-- identify them as legacy rather than pretending that their provider/runtime
-- has semantic guarantees.  The hash is a deterministic digest of the
-- persisted descriptor, never a made-up source or provider claim.
update embedding_generations
   set input_strategy=coalesce(nullif(input_strategy,''),'legacy-unit-v1'),
       runtime=coalesce(nullif(runtime,''),'legacy'),
       configuration_hash=coalesce(
         configuration_hash,
         encode(
           digest(
             jsonb_build_object(
               'provider',provider,
               'model',model,
               'model_revision',model_revision,
               'dimensions',dimensions,
               'normalization',normalization,
               'configuration_version',configuration_version,
               'corpus_revision',corpus_revision
             )::text,
             'sha256'
           ),
           'hex'
         )
       );

alter table embedding_generations
  alter column input_strategy set default 'legacy-unit-v1',
  alter column input_strategy set not null,
  alter column runtime set default 'legacy',
  alter column runtime set not null,
  alter column configuration_hash set default encode(digest('legacy-configuration','sha256'),'hex'),
  alter column configuration_hash set not null;

alter table embedding_generations
  drop constraint if exists embedding_generations_status_check,
  drop constraint if exists embedding_generations_descriptor_check,
  drop constraint if exists embedding_generations_configuration_hash_check;

alter table embedding_generations
  add constraint embedding_generations_status_check check (
    status in ('REQUESTED','BUILDING','READY','ACTIVE','RETIRED','STALE','FAILED')
  ),
  add constraint embedding_generations_descriptor_check check (
    dimensions between 1 and 2000
    and length(trim(input_strategy)) > 0
    and length(trim(runtime)) > 0
  ),
  add constraint embedding_generations_configuration_hash_check check (
    configuration_hash ~ '^[a-f0-9]{64}$'
  );

-- The old signature omitted input strategy, dimensions and configuration
-- hash, so retaining it would reject valid side-by-side deterministic and
-- semantic generations.  The new descriptor index is the sole identity for a
-- generation within a vault and corpus revision.
-- PostgreSQL truncated the constraint name generated by migration 004 before
-- migration 015 introduced vault scope.  Drop both the generated/truncated
-- legacy name and the later explicit index so two vaults in one space can use
-- the same provider descriptor without colliding.
alter table embedding_generations
  drop constraint if exists embedding_generations_space_id_provider_model_model_revisio_key,
  drop constraint if exists embedding_generations_space_id_provider_model_model_revision_configuration_version_corpus_revision_key;
drop index if exists embedding_generations_vault_signature_idx;
create unique index embedding_generations_descriptor_idx
  on embedding_generations(
    vault_id,provider,model,model_revision,dimensions,normalization,
    input_strategy,configuration_version,runtime,configuration_hash,
    corpus_revision
  )
  where vault_id is not null;

create index embedding_generations_scope_status_idx
  on embedding_generations(space_id,vault_id,corpus_revision,status,created_at desc);

-- Legacy indexers could leave more than one ACTIVE shard per vault. Preserve
-- the most recently activated generation and retire the rest before enforcing
-- the single-generation invariant, so an upgrade is deterministic rather
-- than failing while the unique index is created.
with ranked_active as (
  select id,row_number() over (
    partition by vault_id
    order by activated_at desc nulls last,created_at desc,id desc
  ) active_rank
    from embedding_generations
   where vault_id is not null and status='ACTIVE'
)
update embedding_generations g
   set status='RETIRED',retired_at=coalesce(g.retired_at,now()),updated_at=now()
  from ranked_active r
 where g.id=r.id and r.active_rank>1;

create unique index embedding_generations_one_active_per_vault_idx
  on embedding_generations(vault_id)
  where vault_id is not null and status='ACTIVE';

-- An index on an unbounded pgvector column is unsafe because pgvector needs a
-- fixed dimension for its operator class. Drop the old vector(64) index and
-- recreate safe partial expression indexes below.
drop index if exists unit_embeddings_vector_idx;
alter table unit_embeddings
  alter column embedding type vector using embedding::vector,
  add column if not exists embedding_dimensions integer;

update unit_embeddings e
   set embedding_dimensions=g.dimensions
  from embedding_generations g
 where g.id=e.generation_id
   and e.embedding_dimensions is null;

alter table unit_embeddings
  alter column embedding_dimensions set default 64,
  alter column embedding_dimensions set not null;

alter table unit_embeddings
  drop constraint if exists unit_embeddings_embedding_dimensions_check;

alter table unit_embeddings
  add constraint unit_embeddings_embedding_dimensions_check check (
    embedding_dimensions between 1 and 2000
    and vector_dims(embedding)=embedding_dimensions
  );

create index unit_embeddings_generation_idx
  on unit_embeddings(generation_id,unit_id);

-- Keep each supported production/query dimension independently indexable.
-- Future dimensions may still be stored safely, but are intentionally not
-- treated as indexed until their query path defines a fixed cast and a
-- benchmark-backed operator class.
create index unit_embeddings_64_vector_idx
  on unit_embeddings using hnsw ((embedding::vector(64)) vector_cosine_ops)
  where embedding_dimensions=64;

create index unit_embeddings_384_vector_idx
  on unit_embeddings using hnsw ((embedding::vector(384)) vector_cosine_ops)
  where embedding_dimensions=384;

create or replace function akp_validate_unit_embedding()
returns trigger
language plpgsql
as $function$
declare
  generation record;
  unit_record record;
begin
  select g.id,g.space_id,g.vault_id,g.corpus_revision,g.dimensions,g.status
    into generation
    from embedding_generations g
   where g.id=new.generation_id;
  if not found then
    raise exception 'EMBEDDING_GENERATION_NOT_FOUND';
  end if;

  if generation.status <> 'BUILDING' then
    raise exception 'GENERATION_NOT_BUILDING';
  end if;

  select u.space_id,u.vault_id,u.corpus_revision,u.content_hash,u.embedding_eligible
    into unit_record
    from knowledge_units u
   where u.id=new.unit_id;
  if not found then
    raise exception 'KNOWLEDGE_UNIT_NOT_FOUND';
  end if;

  if unit_record.space_id is distinct from generation.space_id
     or unit_record.vault_id is distinct from generation.vault_id
     or unit_record.corpus_revision is distinct from generation.corpus_revision then
    raise exception 'EMBEDDING_SCOPE_MISMATCH';
  end if;

  if new.content_hash is distinct from unit_record.content_hash then
    raise exception 'EMBEDDING_CONTENT_HASH_MISMATCH';
  end if;

  if unit_record.embedding_eligible is not true then
    raise exception 'EMBEDDING_UNIT_NOT_ELIGIBLE';
  end if;

  if new.embedding_dimensions is distinct from generation.dimensions
     or vector_dims(new.embedding) is distinct from generation.dimensions then
    raise exception 'EMBEDDING_DIMENSION_MISMATCH';
  end if;
  return new;
end;
$function$;

drop trigger if exists unit_embeddings_validate_generation
  on unit_embeddings;
create trigger unit_embeddings_validate_generation
before insert or update on unit_embeddings
for each row execute function akp_validate_unit_embedding();

create or replace function akp_validate_embedding_generation_update()
returns trigger
language plpgsql
as $function$
begin
  if new.space_id is distinct from old.space_id
     or new.vault_id is distinct from old.vault_id
     or new.corpus_revision is distinct from old.corpus_revision
     or new.provider is distinct from old.provider
     or new.model is distinct from old.model
     or new.model_revision is distinct from old.model_revision
     or new.dimensions is distinct from old.dimensions
     or new.normalization is distinct from old.normalization
     or new.input_strategy is distinct from old.input_strategy
     or new.configuration_version is distinct from old.configuration_version
     or new.runtime is distinct from old.runtime
     or new.configuration_hash is distinct from old.configuration_hash then
    raise exception 'EMBEDDING_GENERATION_DESCRIPTOR_IMMUTABLE';
  end if;

  if new.status is distinct from old.status
     and not (
       (old.status='REQUESTED' and new.status in ('BUILDING','FAILED','STALE'))
       or (old.status='BUILDING' and new.status in ('READY','FAILED','STALE'))
       or (old.status='READY' and new.status in ('ACTIVE','RETIRED','STALE'))
       or (old.status='ACTIVE' and new.status in ('RETIRED','STALE'))
       or (old.status='RETIRED' and new.status in ('ACTIVE','BUILDING'))
       or (old.status in ('FAILED','STALE') and new.status in ('BUILDING','RETIRED'))
     ) then
    raise exception 'INVALID_EMBEDDING_GENERATION_TRANSITION';
  end if;

  if new.status='ACTIVE' and old.status not in ('READY','RETIRED') then
    raise exception 'EMBEDDING_GENERATION_NOT_READY';
  end if;
  if new.status='ACTIVE' then
    new.activated_at=coalesce(new.activated_at,now());
    new.retired_at=null;
  elsif old.status='ACTIVE' and new.status in ('RETIRED','STALE') then
    new.retired_at=coalesce(new.retired_at,now());
  end if;
  if new.status='BUILDING' then
    new.failure_reason=null;
  end if;
  new.updated_at=now();
  return new;
end;
$function$;

drop trigger if exists embedding_generations_validate_update
  on embedding_generations;
create trigger embedding_generations_validate_update
before update on embedding_generations
for each row execute function akp_validate_embedding_generation_update();

-- One statement performs the whole switch.  The advisory transaction lock is
-- keyed by vault so concurrent activations serialize before retiring the old
-- generation; the partial unique index remains a final database invariant.
create or replace function akp_activate_embedding_generation(p_generation_id uuid)
returns setof embedding_generations
language plpgsql
as $function$
declare
  target embedding_generations;
begin
  select * into target
    from embedding_generations
   where id=p_generation_id
   for update;
  if not found then
    raise exception 'EMBEDDING_GENERATION_NOT_FOUND';
  end if;
  if target.vault_id is null then
    raise exception 'VAULT_SCOPE_REQUIRED';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(target.vault_id::text,0));
  select * into target
    from embedding_generations
   where id=p_generation_id
   for update;
  if target.status='ACTIVE' then
    return query select * from embedding_generations where id=target.id;
    return;
  end if;
  if target.status not in ('READY','RETIRED') then
    raise exception 'EMBEDDING_GENERATION_NOT_READY';
  end if;

  update embedding_generations
     set status='RETIRED',retired_at=coalesce(retired_at,now()),updated_at=now()
   where space_id=target.space_id
     and vault_id=target.vault_id
     and status='ACTIVE'
     and id<>target.id;

  update embedding_generations
     set status='ACTIVE',activated_at=coalesce(activated_at,now()),
         retired_at=null,updated_at=now()
   where id=target.id;

  return query
  select * from embedding_generations where id=target.id;
end;
$function$;
